admin_vat:
    pattern: /admin/params
    defaults: { _controller: AdagyoAdminBundle:Admin:vat }

homepage:
    pattern:  /
    defaults: { _controller: AdagyoFA69Bundle:Home:index }

bill_create:
    pattern:  /bill/new
    defaults: { _controller: AdagyoFA69Bundle:Bill:new }
    requirements:
        _method: GET

bill_search:
    pattern: /bills/{customerid}
    defaults: { _controller: AdagyoFA69Bundle:Bill:search, customerid: '' }
    requirements:
        _method: GET
        customerid: \d+

cust_search:
    pattern: /cutomers
    defaults: { _controller: AdagyoFA69Bundle:Customer:search }
    requirements:
        _method: GET

cust_edit:
    pattern: /cutomers/{id}
    defaults: { _controller: AdagyoFA69Bundle:Customer:edit }
    requirements:
        _method: GET
        id: \d+

utils_changepassword_success:
    pattern: /profile/change-password-success
    defaults: { _controller: AdagyoFA69Bundle:Utils:changePasswordSuccess }

stats:
    pattern: /stats
    defaults: { _controller: AdagyoStatsBundle:Stats:index }

ajax_customer:
    pattern: /ajax/customer
    defaults: { _controller: AdagyoFA69Bundle:Ajax:getCustomer }
    requirements:
        _method: GET

ajax_customer_save:
    pattern: /ajax/customer/save
    defaults: { _controller: AdagyoFA69Bundle:Ajax:saveCustomer }
    requirements:
        _method: POST

ajax_customer_edit:
    pattern: /ajax/customer/edit
    defaults: { _controller: AdagyoFA69Bundle:Ajax:editCustomer }
    requirements:
        _method: POST

ajax_car:
    pattern: /ajax/car
    defaults: { _controller: AdagyoFA69Bundle:Ajax:getCar }
    requirements:
        _method: GET

ajax_car_save:
    pattern: /ajax/car/save
    defaults: { _controller: AdagyoFA69Bundle:Ajax:saveCar }
    requirements:
        _method: POST

ajax_car_edit:
    pattern: /ajax/car/edit
    defaults: { _controller: AdagyoFA69Bundle:Ajax:editCar }
    requirements:
        _method: POST

ajax_product:
    pattern: /ajax/product
    defaults: { _controller: AdagyoFA69Bundle:Ajax:getProduct }
    requirements:
        _method: GET

ajax_bill_search:
    pattern: /ajax/bill/search
    defaults: { _controller: AdagyoFA69Bundle:Ajax:searchBill }
    requirements:
            _method: POST

ajax_customer_search:
    pattern: /ajax/customer/search
    defaults: { _controller: AdagyoFA69Bundle:Ajax:searchCustomer }
    requirements:
            _method: POST

ajax_bill_preview:
    pattern: /ajax/bill/preview
    defaults: { _controller: AdagyoFA69Bundle:Ajax:previewBill }
    requirements:
            _method: POST

ajax_bill_save:
    pattern: /ajax/bill/save
    defaults: { _controller: AdagyoFA69Bundle:Ajax:saveBill }
    requirements:
            _method: POST

ajax_bill_pdf:
    pattern: /ajax/bill/pdf
    defaults: { _controller: AdagyoFA69Bundle:Ajax:getBill }
    requirements:
            _method: POST

ajax_vat_save:
    pattern: /ajax/vat/save
    defaults: { _controller: AdagyoFA69Bundle:Ajax:saveVat }
    requirements:
            _method: POST

ajax_stats_ca:
    pattern: /ajax/stats/ca
    defaults: { _controller: AdagyoFA69Bundle:Ajax:statsCa }
    requirements:
            _method: GET

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile