<?php

namespace Adagyo\FA69Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * billRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class billRepository extends EntityRepository {
    public function getBillsByCustomerId($custumerId, $dateFrom = null, $dateTo = null) {
        $bills = $this->createQueryBuilder('b')
                      ->join('b.customer', 'cust')
                      ->where('cust.id = :customerId')
                        ->setParameter('customerId', $custumerId)
                      ->orderBy('b.date', 'ASC');
        if($dateFrom) {
            $bills->andWhere('b.date >= :dateFrom')->setParameter('dateFrom', $dateFrom);
        }
        if($dateTo) {
            $bills->andWhere('b.date <= :dateTo')->setParameter('dateTo', $dateTo);
        }

        return $bills->getQuery()->getResult();
    }

    public function getBillsByDates($dateFrom = null, $dateTo = null) {
        $bills = $this->createQueryBuilder('b')
            ->orderBy('b.date', 'ASC');
        if($dateFrom) {
            $bills->andWhere('b.date >= :dateFrom')->setParameter('dateFrom', $dateFrom);
        }
        if($dateTo) {
            $bills->andWhere('b.date <= :dateTo')->setParameter('dateTo', $dateTo);
        }

        return $bills->getQuery()->getResult();
    }
}
