<?php

namespace Adagyo\FA69Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * vatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vatRepository extends EntityRepository {
    public function getCurrentVAT() {
        return $this->createQueryBuilder('v')->where('v.isCurrent = :vrai')->setParameter('vrai', true)->getQuery()->getResult()[0];
    }
}
