parameters:
#    adagyo_fa69.example.class: Adagyo\FA69Bundle\Example

services:
#    adagyo_fa69.example:
#        class: %adagyo_fa69.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
